CREATE TABLE IF NOT EXISTS posts (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    content VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (

    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME varchar(50),
    LAST_NAME varchar(50),
    EMAIL varchar(50),
    PASSWORD varchar(40)

);


CREATE TABLE IF NOT EXISTS CURRENCY(

      ID smallint NOT NULL AUTO_INCREMENT PRIMARY KEY,
      ISO_CODE varchar(3) UNIQUE,
      FULL_NAME varchar(50)
);


CREATE TABLE IF NOT EXISTS ACCOUNT_TYPE (

      ID smallint NOT NULL AUTO_INCREMENT PRIMARY KEY,
      CODE varchar(3) UNIQUE,
      BUSINESS_NAME varchar(50)
);

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPE (
      ID smallint NOT NULL AUTO_INCREMENT PRIMARY KEY,
      NAME varchar(10) UNIQUE
 );


CREATE TABLE IF NOT EXISTS ACCOUNT (

    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT REFERENCES CUSTOMER(ID),
    UNIQUE_NO varchar(20),
    NAME varchar(50),
    TYPE smallint REFERENCES ACCOUNT_TYPE(ID),
    CURRENCY smallint REFERENCES CURRENCY(ID),
    OPENING_BALANCE double

);

CREATE TABLE IF NOT EXISTS ACCOUNT_TRANSACTION (

    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT REFERENCES ACCOUNT(ID),
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TRANSACTION_VALUE double,
    TYPE smallint REFERENCES TRANSACTION_TYPE(ID)

);